const { query } = require("../config/database");
const { withSieve } = require("./ManageSieveClient");

const SCRIPT_NAME = process.env.SIEVE_SCRIPT_NAME || "pulsemail";

const useMockData =
    process.env.NODE_ENV === "development" &&
    process.env.USE_MOCK_DATA === "true";

/**
 * Server-side mail filtering and out-of-office, backed by Dovecot Sieve.
 *
 * Rules and vacation settings are stored structurally in Postgres and the
 * `.sieve` script is regenerated from them on every change. Treating the
 * database as the source of truth avoids having to parse Sieve back into a
 * form the UI can edit, which is where most webmail filter editors fall over.
 */

const quote = (value) => `"${String(value).replace(/(["\\])/g, "\\$1")}"`;

const TEST_BUILDERS = {
    from: (match, value) => `header ${match} "from" ${quote(value)}`,
    to: (match, value) => `header ${match} ["to", "cc"] ${quote(value)}`,
    subject: (match, value) => `header ${match} "subject" ${quote(value)}`,
    body: (_match, value) => `body :text :contains ${quote(value)}`,
    header: (match, value, field) =>
        `header ${match} ${quote(field || "x-spam-flag")} ${quote(value)}`,
};

const MATCH_TYPES = {
    contains: ":contains",
    is: ":is",
    matches: ":matches",
};

const buildTest = (condition) => {
    const builder = TEST_BUILDERS[condition.field];
    if (!builder) return null;

    const match = MATCH_TYPES[condition.match] || ":contains";
    const test = builder(match, condition.value, condition.header);

    return condition.negate ? `not ${test}` : test;
};

const ACTION_BUILDERS = {
    fileinto: (action) => `fileinto :create ${quote(action.folder)};`,
    copy: (action) => `fileinto :copy :create ${quote(action.folder)};`,
    redirect: (action) => `redirect ${quote(action.to)};`,
    discard: () => "discard;",
    reject: (action) => `reject ${quote(action.reason || "Message rejected")};`,
    keep: () => "keep;",
    flag: (action) => `addflag ${quote(action.flag || "\\\\Flagged")};`,
    markread: () => 'addflag "\\\\Seen";',
};

const buildActions = (actions = []) => {
    const lines = actions
        .map((action) => ACTION_BUILDERS[action.type]?.(action))
        .filter(Boolean);

    return lines.length > 0 ? lines : ["keep;"];
};

const requiredExtensions = (rules, vacation) => {
    const extensions = new Set(["fileinto", "mailbox"]);

    for (const rule of rules) {
        for (const action of rule.actions || []) {
            if (action.type === "copy") extensions.add("copy");
            if (action.type === "reject") extensions.add("reject");
            if (action.type === "flag" || action.type === "markread") {
                extensions.add("imap4flags");
            }
        }
        for (const condition of rule.conditions || []) {
            if (condition.field === "body") extensions.add("body");
        }
    }

    if (vacation?.enabled) {
        extensions.add("vacation");
        if (vacation.startDate || vacation.endDate) {
            extensions.add("date");
            extensions.add("relational");
        }
    }

    return [...extensions];
};

/**
 * Render the complete personal Sieve script. Rules run in priority order and
 * `stop;` ends processing so later rules cannot undo an earlier decision.
 */
const generateScript = (rules = [], vacation = null) => {
    const active = rules.filter((rule) => rule.active !== false);
    const extensions = requiredExtensions(active, vacation);

    const lines = [
        "# Generated by Pulsemail. Manual edits will be overwritten.",
        `require [${extensions.map(quote).join(", ")}];`,
        "",
    ];

    if (vacation?.enabled) {
        const guards = [];
        if (vacation.startDate) {
            guards.push(
                `currentdate :value "ge" "iso8601" ${quote(vacation.startDate)}`
            );
        }
        if (vacation.endDate) {
            guards.push(
                `currentdate :value "le" "iso8601" ${quote(vacation.endDate)}`
            );
        }

        const vacationCommand = [
            "vacation",
            `:days ${Math.max(1, parseInt(vacation.intervalDays, 10) || 7)}`,
            vacation.subject ? `:subject ${quote(vacation.subject)}` : "",
            `${quote(vacation.body || "I am currently away.")};`,
        ]
            .filter(Boolean)
            .join(" ");

        if (guards.length > 0) {
            lines.push(`if allof (${guards.join(", ")}) {`);
            lines.push(`    ${vacationCommand}`);
            lines.push("}", "");
        } else {
            lines.push(vacationCommand, "");
        }
    }

    for (const rule of active) {
        const tests = (rule.conditions || []).map(buildTest).filter(Boolean);
        if (tests.length === 0) continue;

        const combinator = rule.match === "any" ? "anyof" : "allof";
        const condition =
            tests.length === 1 ? tests[0] : `${combinator} (${tests.join(", ")})`;

        lines.push(`# ${rule.name || "rule"}`);
        lines.push(`if ${condition} {`);
        for (const action of buildActions(rule.actions)) {
            lines.push(`    ${action}`);
        }
        if (rule.stopProcessing !== false) lines.push("    stop;");
        lines.push("}", "");
    }

    return lines.join("\n");
};

class SieveService {
    static async getRules(mailbox) {
        const result = await query(
            `SELECT id, name, priority, match_type, conditions, actions,
                    stop_processing, active
               FROM mail_filters
              WHERE user_email = $1
              ORDER BY priority, id`,
            [mailbox]
        );

        return result.rows.map((row) => ({
            id: row.id,
            name: row.name,
            priority: row.priority,
            match: row.match_type,
            conditions: row.conditions || [],
            actions: row.actions || [],
            stopProcessing: row.stop_processing,
            active: row.active,
        }));
    }

    static async saveRule(mailbox, rule) {
        const payload = [
            mailbox,
            rule.name || "Untitled rule",
            rule.priority ?? 0,
            rule.match === "any" ? "any" : "all",
            JSON.stringify(rule.conditions || []),
            JSON.stringify(rule.actions || []),
            rule.stopProcessing !== false,
            rule.active !== false,
        ];

        const result = rule.id
            ? await query(
                  `UPDATE mail_filters
                      SET name = $2, priority = $3, match_type = $4,
                          conditions = $5, actions = $6, stop_processing = $7,
                          active = $8, updated_at = NOW()
                    WHERE user_email = $1 AND id = $9
                RETURNING id`,
                  [...payload, rule.id]
              )
            : await query(
                  `INSERT INTO mail_filters
                      (user_email, name, priority, match_type, conditions,
                       actions, stop_processing, active)
                   VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
                RETURNING id`,
                  payload
              );

        await SieveService.publish(mailbox);
        return result.rows[0]?.id;
    }

    static async deleteRule(mailbox, id) {
        await query(
            "DELETE FROM mail_filters WHERE user_email = $1 AND id = $2",
            [mailbox, id]
        );
        await SieveService.publish(mailbox);
        return true;
    }

    static async getVacation(mailbox) {
        const result = await query(
            `SELECT enabled, subject, body, start_date, end_date, interval_days
               FROM vacation_settings
              WHERE user_email = $1`,
            [mailbox]
        );

        const row = result.rows[0];
        if (!row) {
            return {
                enabled: false,
                subject: "Out of office",
                body: "",
                startDate: null,
                endDate: null,
                intervalDays: 7,
            };
        }

        return {
            enabled: row.enabled,
            subject: row.subject,
            body: row.body,
            startDate: row.start_date,
            endDate: row.end_date,
            intervalDays: row.interval_days,
        };
    }

    static async setVacation(mailbox, settings) {
        await query(
            `INSERT INTO vacation_settings
                (user_email, enabled, subject, body, start_date, end_date,
                 interval_days, updated_at)
             VALUES ($1, $2, $3, $4, $5, $6, $7, NOW())
             ON CONFLICT (user_email) DO UPDATE
                SET enabled = $2, subject = $3, body = $4, start_date = $5,
                    end_date = $6, interval_days = $7, updated_at = NOW()`,
            [
                mailbox,
                settings.enabled === true,
                settings.subject || "Out of office",
                settings.body || "",
                settings.startDate || null,
                settings.endDate || null,
                Math.max(1, parseInt(settings.intervalDays, 10) || 7),
            ]
        );

        await SieveService.publish(mailbox);
        return SieveService.getVacation(mailbox);
    }

    static async preview(mailbox) {
        const [rules, vacation] = await Promise.all([
            SieveService.getRules(mailbox),
            SieveService.getVacation(mailbox),
        ]);
        return generateScript(rules, vacation);
    }

    /**
     * Regenerate and upload the script. A ManageSieve failure is reported but
     * never rolls back the stored rules, so the UI stays usable when Dovecot's
     * sieve service is unreachable.
     */
    static async publish(mailbox) {
        const script = await SieveService.preview(mailbox);

        if (useMockData) {
            return { published: false, reason: "mock mode", script };
        }

        try {
            await withSieve(mailbox, async (client) => {
                await client.putScript(SCRIPT_NAME, script);
                await client.setActive(SCRIPT_NAME);
            });
            return { published: true, script };
        } catch (error) {
            console.error(
                `Failed to publish sieve script for ${mailbox}:`,
                error.message
            );
            return { published: false, reason: error.message, script };
        }
    }
}

module.exports = { SieveService, generateScript };
